services:
  iris:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 1974:1972
      - 52777:52773
      - 5547:5547
    volumes:
      - ./:/home/irisowner/dev 